id: I0D864188
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T07:06:24+00:00'
last_modified: '2022-06-08T02:55:51.835314+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC385
  title: 'བཅོམ་ལྡན་འདས་དཔལ་འཇིག་རྟེན་དབང་ཕྱུག་གི་ཆོ་གའི་ཟིན་བྲིས་རབ་གསལ་ཐར་པའི་ལམ་ཆེན་ལས་བདག་བསྐྱེད་ཀྱི་དཀའ་བའི་གནད་རྣམས་བཀྲོལ་བ་དོན་འགྲེལ་ཉི་མའི་འོད་ཟེར། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5E82:
      image_group_id: I2PD18237
      title: ''
      total_pages: 502
      order: 1
      base_file: 5E82.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
