id: P005416
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC385
  title: 'བཅོམ་ལྡན་འདས་དཔལ་འཇིག་རྟེན་དབང་ཕྱུག་གི་ཆོ་གའི་ཟིན་བྲིས་རབ་གསལ་ཐར་པའི་ལམ་ཆེན་ལས་བདག་བསྐྱེད་ཀྱི་དཀའ་བའི་གནད་རྣམས་བཀྲོལ་བ་དོན་འགྲེལ་ཉི་མའི་འོད་ཟེར། '
  author: ''
  volumes: {}
